////////////////////////////////////////////////////////////////////////
// Class:       OpHitSaturationCorrection
// Module Type: producer
// File:        OpHitSaturationCorrection_module.cc
//
// Created: June 16 by Laura Paulucci (lpaulucc@fnal.gov)
//
// This module works on OpticalHits to identify and correct saturation using a ToS method.
// It reads in the OpHits already stored by the classical OpHitFinder then retroactively 
// looks at the raw waveforms to recalculate the hit area based on the saturation duration. 
// This module produces a new set of OpHits that should be
// used as input to the OpFlashFinder
////////////////////////////////////////////////////////////////////////

//LArSoft includes
#include "lardataobj/RawData/OpDetWaveform.h"
#include "lardataobj/RecoBase/OpHit.h"
#include "larcore/CoreUtils/ServiceUtil.h"
#include "larcore/Geometry/WireReadout.h"
#include "lardata/Utilities/AssociationUtil.h"
#include "lardata/DetectorInfoServices/DetectorClocksService.h"
#include "canvas/Persistency/Common/FindOneP.h"

//Framework includes
#include "art/Framework/Core/EDProducer.h"
#include "art/Framework/Core/ModuleMacros.h"
#include "art/Persistency/Common/PtrMaker.h"
#include "canvas/Persistency/Common/Ptr.h"
#include "canvas/Persistency/Common/PtrVector.h"
#include "art/Framework/Principal/Event.h"
#include "art/Framework/Principal/Handle.h"
#include "art/Framework/Principal/Run.h"
#include "art/Framework/Principal/SubRun.h"
#include "fhiclcpp/ParameterSet.h"
#include "messagefacility/MessageLogger/MessageLogger.h"
#include "canvas/Utilities/Exception.h"
#include "cetlib_except/exception.h"

//C++ includes
#include <memory>
#include <cmath>
#include <fstream>
#include <iostream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

namespace opdet{

  class OpHitSaturationCorrection;

  class OpHitSaturationCorrection : public art::EDProducer {
  public:
    OpHitSaturationCorrection(fhicl::ParameterSet const & p);
    // The destructor generated by the compiler is fine for classes
    // without bare pointers or other resource use.

    // Plugins should not be copied or assigned.
    OpHitSaturationCorrection(OpHitSaturationCorrection const &) = delete;
    OpHitSaturationCorrection(OpHitSaturationCorrection &&) = delete;
    OpHitSaturationCorrection & operator = (OpHitSaturationCorrection const &) = delete;
    OpHitSaturationCorrection & operator = (OpHitSaturationCorrection &&) = delete;

    // Required functions.
    void produce(art::Event & evt) override;
    bool CheckSaturation(std::vector<short int> wf, short int StartTick, short int EndTick, int PeakAmplitude);
    void AreaCorrection(double TickTous, std::vector<double> calibvec, double calibThrs, double& newArea, short int StartTick, short int EndTick, std::vector<short int> wf);
    double CalibCurve(std::vector<double> calibvec, double ToT);

  private:
    // Declare member data here.
    double newArea;
    double newPE;
    // The parameters read from the fcl file.
    std::string fOpHitModuleLabel; // Input tag for OpHit collection
    std::vector<int> fIgnoreChannels;
    std::vector<size_t> fchannelVec; //list of channels for which the calibration exists
    std::vector<double> fcalibParam1; //calibration parameter 1
    std::vector<double> fcalibParam2; //calibration parameter 2
    std::vector<double> fcalibParam3; //calibration parameter 3
    double fcalibThrs;
    std::map<size_t, std::vector<double>> fCalibMap; //Map to store the calibration parameters for different channels
  };
}//namespace opdet

namespace opdet {

  DEFINE_ART_MODULE(OpHitSaturationCorrection)

}

namespace opdet {

  OpHitSaturationCorrection::OpHitSaturationCorrection(fhicl::ParameterSet const &p)
   : EDProducer{p}
  // Initialize member data here.
  {
    // Indicate that the Input Module comes from .fcl
    fOpHitModuleLabel        = p.get<std::string>("OpHitModuleLabel"); 
    fIgnoreChannels          = p.get<std::vector<int> >("IgnoreChannels");
    fcalibThrs               = p.get<double>("calibThrs");     //Value at which the calibration curve was evaluated
    fchannelVec              = p.get<std::vector<size_t> >("channelVec");
    fcalibParam1             = p.get<std::vector<double> >("calibParam1");
    fcalibParam2             = p.get<std::vector<double> >("calibParam2");
    fcalibParam3             = p.get<std::vector<double> >("calibParam3");
 
    // This module produces (infrastructure piece)
    produces<std::vector<recob::OpHit>>();
    produces<art::Assns<recob::OpHit, raw::OpDetWaveform>>();
  }

  void OpHitSaturationCorrection::produce(art::Event & evt)
  {
    // Corrected OpHits and association between OpHits and waveforms
    auto correctedHits = std::make_unique<std::vector<recob::OpHit>>();
    auto hit_wf_assns  = std::make_unique<art::Assns<recob::OpHit, raw::OpDetWaveform>>();
    art::PtrMaker<recob::OpHit> makeHitPtr{evt};

    std::cout << "\nRunning Saturation Correction algo\n";
    // Load hits into HitVector
    auto const opHitHandle = evt.getValidHandle<std::vector<recob::OpHit>>(fOpHitModuleLabel);
    //Get the Hit-Waveform association
    art::FindOneP<raw::OpDetWaveform> findWaveform(opHitHandle, evt, fOpHitModuleLabel);

    assert(opHitHandle.isValid());

    //Get detector clock info
    auto const clockData = art::ServiceHandle<detinfo::DetectorClocksService const>()->DataForJob();

    //Create the calibration map
    for(size_t i=0; i<fchannelVec.size(); i++){
     fCalibMap[fchannelVec.at(i)]={fcalibParam1.at(i), fcalibParam2.at(i), fcalibParam3.at(i)}; 
    }

    for (size_t i=0; i<opHitHandle->size(); i++) {
      if (opHitHandle->size() == 0 ) {
        mf::LogInfo("OpHitSaturationCorrection") << "Empty hits, continue.";
        continue;
      }
      art::Ptr<recob::OpHit> hitPtr(opHitHandle, i);
      art::Ptr<raw::OpDetWaveform> wvfPtr = findWaveform.at(i);

      if(std::find(fIgnoreChannels.begin(), fIgnoreChannels.end(), hitPtr->OpChannel()) != fIgnoreChannels.end()) continue;

      int PeakAmplitude = hitPtr->Amplitude();
      newArea=hitPtr->Area();
      const std::vector<short>& wf = wvfPtr->Waveform();
      short int StartTick = ( hitPtr->StartTime() - wvfPtr->TimeStamp() + clockData.TriggerTime() ) / clockData.OpticalClock().TickPeriod(); //Ophit start tick PRECISA CONVERTER UNIDADES!!!
      short int EndTick =  StartTick + hitPtr->Width()*1000 / clockData.OpticalClock().TickPeriod(); //Ophit end tick
      if(!CheckSaturation(wf, StartTick, EndTick, PeakAmplitude)){newPE=hitPtr->PE();} // peak is not saturated
      else{ //peak is saturated and needs to be corrected
        AreaCorrection(clockData.OpticalClock().TickPeriod(), fCalibMap[hitPtr->OpChannel()], fcalibThrs, newArea, StartTick, EndTick, wf); //Update area value
        newPE=newArea*hitPtr->PE()/hitPtr->Area(); //Update PE value
      }

      correctedHits->emplace_back(hitPtr->OpChannel(),
                                  hitPtr->PeakTime(),// + clockData.TriggerTime(), Should we include the data correction here already???
                                  hitPtr->PeakTimeAbs(),
                                  hitPtr->StartTime(),// + clockData.TriggerTime(), SAME HERE?
                                  hitPtr->RiseTime(),
                                  hitPtr->Frame(),
                                  hitPtr->Width(),
                                  newArea,
                                  hitPtr->Amplitude(),
                                  newPE,
                                  0.0);

      // create a art pointer to that ophit (now the last one in the collection)
      art::Ptr<recob::OpHit> newOphitPtr = makeHitPtr(correctedHits->size() - 1);
      // add an association tothe waveform in the ophit list
//      for(art::Ptr<raw::OpDetWaveform> const&amp; hitPtr: clusterHits)
//      hit_wf_assns->addSingle(newOphitPtr, hitPtr);   
    //Maintain the association to the waveform
   // util::CreateAssn(*this, evt, *correctedHits,wvfPtr,*hit_wf_assns);
   // util::CreateAssn(evt, *correctedHits, wvfPtr, *hit_wf_assns);
      hit_wf_assns->addSingle(newOphitPtr, wvfPtr);
    }

    // Push the new OpHits and association into the event
    evt.put(std::move(correctedHits));
    evt.put(std::move(hit_wf_assns));
  }

  bool OpHitSaturationCorrection::CheckSaturation(std::vector<short int> wf, short int StartTick, short int EndTick, int PeakAmplitude){
  //Checks if a waveform is saturated (baseline is removed so saturation happens no longer at the same value)
    for(double sample : wf) {
      if(sample == PeakAmplitude && sample++ == PeakAmplitude){
        return true;
      }
    }
    // If we finished the entire waveform without finding two consective bins with the maximum value
    return false;
  }

  void OpHitSaturationCorrection::AreaCorrection(double TickTous, std::vector<double> calibvec, double calibThrs, double& newArea, short int StartTick, short int EndTick, std::vector<short int> wf){
    //For the moment, the correction applied here is based on the "time-over-saturation (ToS)" method, where the missing area is added to the original area calculation
    //(see Maressa's presentation here: https://indico.fnal.gov/event/74741/contributions/342609/attachments/198490/276375/Jun_ToTUpdate_PDVD.pdf)
    double missingArea, ToS=0; //value for which the calib curve was obtained
    short int previous_value=0, first_tick=StartTick; //value of the waveform for tick-- (to check for saturation = plateau)
    while(first_tick<EndTick){ //the same hit can be saturated multiple times
      for(short int i=first_tick; i<EndTick; i++){
        if(wf[i]==previous_value) ToS++; //Checking for plateaus, ToS in ticks 
        else{ previous_value=wf[i]; }
        if(ToS!=0 && wf[i]<previous_value){
          first_tick=i; //point where the peak was evaluated
          break; 
        }
      }
      if(ToS>0){    
        ToS=ToS*TickTous;//converting ticks to us
        missingArea=CalibCurve(calibvec, ToS)*previous_value/calibThrs;
        newArea+=missingArea;
      }
      ToS=0; previous_value=0;
    }
  }

  double OpHitSaturationCorrection::CalibCurve(std::vector<double> calibvec, double ToS){
   // double calibvec[3]={1,1,1}; //parameters of the calib curve, channel dependent, in order: a, b, c
    double area;
    
    area=calibvec[0]*pow(ToS,calibvec[1])*exp(calibvec[2]*ToS);   
    return area;
  }

}//namespace opdet
